### ISSUE TITLE
v1.0.0 release checklist

### ISSUE THREAD

**Issue by kklash** [kklash/mnemonikey#30]
- [x] [`wordlist4096`](https://github.com/kklash/wordlist4096)
    - [x] Remove the warning from the readme
    - [x] Tag `v1.0.0`
- [x] Mnemonikey
    - [x] Bump `wordlist4096` to `v1.0.0`
    - [x] Remove the warning from the readme
    - [x] Tag `v1.0.0` (include binary builds for Linux and MacOS)
